import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const satoshi = localFont({
  src: './fonts/Satoshi-Variable.ttf',
  display: 'swap',
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: 'OpenAI Trivia',
  description: 'Generated by create next app',
};
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={satoshi.variable}>
        <main className="h-screen overflow-auto font-sans">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
